language: node_js
node_js:
  - "8.9.3"
cache:
  yarn: true
  directories:
  - node_modules
  - firebase/functions/node_modules

branches:
  only:
    - master

before_script:
  - cd firebase/functions
  - yarn
  - cd ../..

script:
  - yarn run build --configuration=firebase

deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN
