language: node_js
node_js:
  - "8.9.3"
cache:
  yarn: true
  directories:
  - node_modules
  - firebase/functions/node_modules

branches:
  only:
    - master

before_script:
  - yarn global add firebase-tools
  - cd firebase/functions
  - yarn
  - cd ../..

script:
  - yarn run build --configuration=firebase

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
